# Generated by Django 5.0 on 2023-12-13 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('fio', models.TextField()),
                ('passport', models.TextField()),
                ('country', models.TextField()),
                ('city', models.TextField()),
                ('phone_number', models.TextField()),
                ('email', models.TextField(blank=True, null=True)),
                ('post_index', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('n_carriage', models.DecimalField(decimal_places=0, max_digits=3)),
                ('n_seat', models.DecimalField(decimal_places=0, max_digits=5)),
                ('seat_type', models.TextField()),
                ('seat_availibility', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False)),
                ('train_name', models.TextField()),
                ('train_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField()),
                ('summary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.customer')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TrainRoute',
            fields=[
                ('trainroute_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.train')),
            ],
        ),
        migrations.CreateModel(
            name='TrainStationRout',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('break_period', models.TimeField(blank=True, null=True)),
                ('departure_date', models.DateTimeField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.station')),
                ('train_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.trainroute')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='route_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_from', to='train.trainstationrout'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='route_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_to', to='train.trainstationrout'),
        ),
    ]
