# Generated by Django 5.0 on 2023-12-06 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('fio', models.TextField()),
                ('passport', models.TextField()),
                ('country', models.TextField()),
                ('city', models.TextField()),
                ('phone_number', models.TextField()),
                ('email', models.TextField()),
                ('post_index', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
        migrations.RenameField(
            model_name='route',
            old_name='station_id',
            new_name='station',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='train_id',
            new_name='train',
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('n_carriage', models.DecimalField(decimal_places=0, max_digits=3)),
                ('n_seat', models.DecimalField(decimal_places=0, max_digits=5)),
                ('seat_type', models.TextField()),
                ('seat_availibility', models.TextField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.route')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField()),
                ('summary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.customer')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.ticket')),
            ],
        ),
    ]
